on:
  schedule:
    # runs every day at 10:00 am UTC
    - cron: '0 10 * * *'

jobs:
  update-nixfmt-input:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.SEROKELL_BOT_PAT }}

      - name: update nixfmt input
        run: nix flake lock --update-input nixfmt-src

      - name: commit flake.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: serokell-bot
          commit_user_email: operations+github@serokell.io
          commit_author: serokell-bot <operations+github@serokell.io>
          commit_message: "Update nixfmt input"
          file_pattern: "flake.lock"
